#!/usr/bin/env bash
# Installs nginx server
# Serve a page that would return a Hello World string
sudo apt-get  update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
