#!/usr/bin/env bash
# Installs nginx server
# Serve a page that would return a Hello World string
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
