#!/usr/bin/env bash
# configures an Ubuntu machine with nginx
# FILE="/etc/nginx/sites-available/default"
# ERRORFILE="/usr/share/nginx/html/404error.html"

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
