#!/usr/bin/env bash
# This script displays time for 12 hours and 59 minutes

h=0

while [ $h -le 12 ]
do
	echo "Hour: $h"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( h++ ))
done
